# Generated by Django 6.0 on 2026-02-02 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_profile_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='notes',
        ),
        migrations.AddField(
            model_name='food',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='food_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='food',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='food',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('requested', 'Requested'), ('assigned', 'Assigned to Volunteer'), ('picked', 'Picked Up'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='available', max_length=20),
        ),
    ]
