# Generated by Django 6.0 on 2026-02-02 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_food_notes_food_latitude_food_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
