# Generated by Django 6.0 on 2026-02-03 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_food_requested_by_alter_food_donor'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='pickup_type',
            field=models.CharField(blank=True, choices=[('self', 'Self Pickup'), ('volunteer', 'Volunteer Delivery')], max_length=20, null=True),
        ),
    ]
