# Generated by Django 5.2.10 on 2026-03-16 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_food_id_alter_profile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='kyc_document',
            field=models.FileField(blank=True, null=True, upload_to='kyc_documents/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='kyc_verified',
            field=models.BooleanField(default=False),
        ),
    ]
